# Generated by Django 5.0.2 on 2024-04-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_todolist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='description',
            new_name='date',
        ),
        migrations.AddField(
            model_name='todolist',
            name='time',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
