# Generated by Django 5.0.2 on 2024-04-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_description_todolist_date_todolist_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.TextField(),
        ),
    ]
